### ISSUE TITLE
Delete unapplied migrations

### ISSUE THREAD

**Issue by adamghill** [lorinkoz/django-unmigrate#10]
Firstly, thanks for releasing this! I've had a similar idea kicking around in my head for a while, but never got past 50% in implementing it! :)

I find my Django workflow for local dev to be a lot of: add/tweak model fields, create a migration, test, repeat. Then at the end, I usually un-apply all of the new migrations, delete the migration files, and re-create one new migration file which I then push.

This library seems to work great for the first part! Is there any interest in a PR for the second part (deleting the migration files?). Or would you consider that out of scope for this particular tool?

Thanks again for the project -- it definitely solves an issue that I've had for a while in an elegant way.

**Comment by lorinkoz** [comment]
Sure, can you write the idea as a small proposal before getting to code it?

**Comment by adamghill** [comment]
Sure! This is the way I was thinking about it.

Add an optional `--clean` argument that can be passed into the Django management command. It would only be valid if `--dry-run` or `--fake` isn't in the argument list already. If `--clean` is passed in, the migrations that are found and un-applied would also be deleted using `os.remove()`. By default, there would be a "y/n" confirmation question to make sure that the user knows they are removing the files. Maybe there could be a `--no-input` argument similar to other Django management commands (e.g. `collectstatic`) that would remove the files automatically without needing a confirmation input?

**Comment by lorinkoz** [comment]
One question: unmigrate can unapply migrations that are committed in Git, and not just those within the current stashed/unstashed changes. Will this new option also delete those?

For instance:

```
python manage.py unmigrate HEAD~20 --clean
```

**Comment by adamghill** [comment]
I suppose in that instance it _could_. I guess it depends on what the workflow is like when you unmigrate back to a certain commit. Would you expect the filesystem to reflect the "state" of the database?

**Comment by lorinkoz** [comment]
In the purist side of things, it _should_ clean whatever it unapplies, but in the practical side, you'll almost always want to clean only the uncommited changes. I'll leave that up to you. My only request is that if it won't clean everything that is unmigrated, then you use something a little more explicit than just `clean` for the verbose arg (for instance: `-c, --clean-index` or something like that)

Bring that PR 😉 🎉

**Comment by lorinkoz** [comment]
Apologies for the huge delay. `django-unmigrate` v0.2 is out!
