### ISSUE TITLE
Collaboration brainstorm

### ISSUE THREAD

**Issue by ryanhiebert** [lorinkoz/django-unmigrate#23]
I and my team wrote [django-safemigrate](https://github.com/aspiredu/django-safemigrate) to help us use Heroku's release phase to automatically run migrations. It does this by allowing us to mark whether the migration is safe to run before or after the deployment has successfully rolled out.

Naturally, it would be nice to be able to do something similar when we need to roll a release back. This hasn't been pressing, but I've given some thought as to how that might work.

Would you be interested in a zoom call or something to brainstorm if there's a good approach that will help both of our projects?

**Comment by lorinkoz** [comment]
Absolutely.

**Comment by ryanhiebert** [comment]
Awesome. I'm in central time, USA. I'm available from 8:30 - 14:30 Monday through Thursday my time, which seems to be 9:30 - 15:30 Cuba time. Do you have some time tomorrow, perhaps, or next week? I can create a zoom link and post it here.

**Comment by lorinkoz** [comment]
Sent you an invite with a Google Meet link. I'm unable to use Zoom without VPN so I prefer Google Meet. Talk soon!

**Comment by ryanhiebert** [comment]
Sounds great, thank you!
